
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace bankapp {
    using System;
    using Terminal.Gui;
    
    public partial class LoginView : Terminal.Gui.Window {
        
        private Terminal.Gui.Label usernameFieldLabel;
        private Terminal.Gui.TextField usernameField;
        private Terminal.Gui.Label passwordFieldLabel;
        private Terminal.Gui.TextField passwordField;
        private Terminal.Gui.Button loginButton;
        private Terminal.Gui.Button createAccountButton;
        private Terminal.Gui.Button resetPasswordButton;

        private Terminal.Gui.Label errorMessageLabel;
        
        
        private void InitializeComponent() {

            // Window Settings
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "StealGreens Bank SSL - Login";

            // Component Declarations

            this.usernameField = new Terminal.Gui.TextField();
            this.usernameFieldLabel = new Terminal.Gui.Label();
            this.passwordField = new Terminal.Gui.TextField();
            this.passwordFieldLabel = new Terminal.Gui.Label(); 
            this.loginButton = new Terminal.Gui.Button();
            this.createAccountButton = new Terminal.Gui.Button();
            this.resetPasswordButton = new Terminal.Gui.Button();
            this.errorMessageLabel = new Terminal.Gui.Label();

            // Username Fields

            this.usernameField.Width = 24;
            this.usernameField.Height = 1;

            this.usernameField.X = Pos.Center();
            this.usernameField.Y = Pos.Center() - 3;       
    
            this.usernameFieldLabel.Width = 24;
            this.usernameFieldLabel.Height = 1;
            this.usernameFieldLabel.X = Pos.Center();
            this.usernameFieldLabel.Y = Pos.Center() - 4;
            this.usernameFieldLabel.TextAlignment = TextAlignment.Left;
            this.usernameFieldLabel.Text = "Username";

            // Password Fields

            this.passwordField.Width = 24;
            this.passwordField.Height = 1;
            this.passwordField.X = Pos.Center();
            this.passwordField.Y = Pos.Center() + 0;
            this.passwordField.Secret = true;

            this.passwordFieldLabel.Width = 24;
            this.passwordFieldLabel.Height = 1;
            this.passwordFieldLabel.X = Pos.Center();
            this.passwordFieldLabel.Y = Pos.Center() - 1;
            this.passwordFieldLabel.TextAlignment = TextAlignment.Left;
            this.passwordFieldLabel.Text = "Password";

            // Login Buttons

            this.loginButton.Width = 10;
            this.loginButton.Height = 1;
            this.loginButton.X = Pos.Center() - 12;
            this.loginButton.Y = Pos.Center() + 2;
            this.loginButton.Text = "Login";
            
            this.resetPasswordButton.Width = 10;
            this.resetPasswordButton.Height = 1;
            this.resetPasswordButton.X = Pos.Center() - 1;
            this.resetPasswordButton.Y = Pos.Center() + 2;
            this.resetPasswordButton.Text = "Reset Pwd";
            this.resetPasswordButton.TextAlignment = TextAlignment.Right;

            this.createAccountButton.Width = 24;
            this.createAccountButton.Height = 1;
            this.createAccountButton.X = Pos.Center();
            this.createAccountButton.Y = Pos.Center() + 4;
            this.createAccountButton.Text = "Create Account";

            this.errorMessageLabel.X = Pos.Center();
            this.errorMessageLabel.Y = Pos.Center() + 6;
            this.errorMessageLabel.Text = "Debug Text";
            this.errorMessageLabel.Visible = false;


            // Adding to Screens

            this.Add(this.usernameFieldLabel,
                    this.usernameField,
                    this.passwordFieldLabel,
                    this.passwordField,
                    this.loginButton,
                    this.resetPasswordButton,
                    this.createAccountButton,
                    this.errorMessageLabel);
        }
    }
}
